{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "parasol-web.serviceAccountName" . }}
  labels:
    {{- include "parasol-web.labels" . | nindent 4 }}
{{- end }}
