[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    '''parasol-camel-common\/matrix-synapse\/templates\/configmap.yaml'''
  ]
        
  # Ignore based on any subset of the line
  regexes = []