{{- if and (.Values.db.deploy) (eq .Values.persistence.mode "persistent") -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "parasol-db.name" . }}
  labels:
    {{- include "parasol-db.labels" . | nindent 4 }}
  annotations:
    {{- include "parasol-db.argocd-syncwave" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
{{- end }}