apiVersion: v1
kind: Service
metadata:
  name: {{ include "parasol-store-app.name" . }}
  labels:
    {{- include "parasol-store-app.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.containerPort }}
  selector:
    {{- include "parasol-store-app.selectorLabels" . | nindent 4 }}
