{{- if and .Values.db.deploy .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "parasol-db.serviceAccountName" . }}
  labels:
    {{- include "parasol-db.labels" . | nindent 4 }}
  annotations:
    {{- include "parasol-db.argocd-syncwave" . | nindent 4 }}
{{- end }}
